App-293: Fix apach-rat-check warnings on latest develop
kaaproject/sample-apps pull request #230
Opened 2016-09-15 17:05 UTC by maxml

2016-09-15 18:06 UTC, Slash32 commented on verifiersdemo/pom.xml
> +                            /source/objc/EndpointOwnershipDemo.xcworkspace/contents.xcworkspacedata
This does not seem to be a thirdparty component, thus should not be excluded.

2016-09-15 18:07 UTC, Slash32 commented on verifiersdemo/pom.xml
> +                        <exclude>/source/android/kits.properties</exclude>
Here and below the same as above.

2016-09-15 18:08 UTC, Slash32 requested changes

2016-09-20 11:58 UTC, am1kk commented on verifiersdemo/pom.xml
> +                            /source/objc/EndpointOwnershipDemo.xcworkspace/contents.xcworkspacedata
As a rule, files with the same extension doesn't have license header.

2016-09-20 11:59 UTC, am1kk approved these changes

2016-09-22 09:26 UTC, maxml commented on verifiersdemo/pom.xml
> +                        <exclude>/source/android/kits.properties</exclude>
These files must be excluded. These are generated files, as I remember.

2016-09-22 22:39 UTC, vadimol approved these changes
LGTM

2016-09-22 22:41 UTC, vadimol commented on verifiersdemo/pom.xml
> +                            /source/objc/EndpointOwnershipDemo.xcworkspace/contents.xcworkspacedata
We can discuss it locally and provide a fix in the separate PR. Let's accept this now as a workaround. It is some sort of blocker.

2016-09-22 22:41 UTC, merged