APP-242: [C++] Basic level Appls: Endpoint ownership
kaaproject/sample-apps pull request #237
Opened 2016-09-19 16:18 UTC by Dubland

/cc @Slash32 @RostakaGmfun @vadimol

2016-09-19 17:02 UTC, GamovCoder commented on verifiersdemo/source/cpp/README.txt
> +This demo application illustrate user verifiers feature using the Kaa C++ SDK.
`s/illustrate/illustrates/`

2016-09-19 17:03 UTC, GamovCoder commented on verifiersdemo/source/cpp/README.txt
> +To run the demo application, do the following:
`s/do the following/proceed as follows/g`

2016-09-19 17:03 UTC, GamovCoder commented on verifiersdemo/source/cpp/README.txt
> +1. Install third-party libraries to build the Kaa C SDK.
`s/Kaa C SDK/Kaa C++ SDK/g`

2016-09-19 17:04 UTC, GamovCoder commented on verifiersdemo/source/cpp/README.txt
> +list of third-party dependencies for the Kaa C SDK.
`s/Kaa C SDK/Kaa C++ SDK/g`

2016-09-19 17:04 UTC, GamovCoder commented on verifiersdemo/source/cpp/README.txt
> +3. Generate the C SDK using the Kaa sandbox. The Avro log schema required for the demo application is located in
`s/Kaa C SDK/Kaa C++ SDK/g`

2016-09-19 17:05 UTC, GamovCoder commented on verifiersdemo/source/cpp/README.txt
> +the 'avro' directory. Put the SDK archive into the 'libs/kaa' directory.
`s/archive/tarball/g`

2016-09-19 17:07 UTC, GamovCoder commented on verifiersdemo/source/cpp/src/KaaDemo.cpp
> +    std::cout << DEMO_ACCESS_TOKEN << std::endl;
I'd print the preface which describes what's going to be printed rather than just printing access token out

2016-09-19 17:09 UTC, ohamov requested changes
Reviewed.

2016-09-19 17:09 UTC, ohamov commented on verifiersdemo/source/cpp/CMakeLists.txt
> +project (Cpp-SDK-notification-sample)
redundant space

2016-09-19 17:09 UTC, ohamov commented on verifiersdemo/source/cpp/src/KaaDemo.cpp
> +    virtual void onEvent(const nsVerifiersDemoEventClassFamily::MessageEvent& event, const std::string& source)
remove `virtual` key word & add `override` one please

2016-09-19 17:09 UTC, ohamov commented on verifiersdemo/source/cpp/src/KaaDemo.cpp
> +    VerifiersDemoEventClassFamilyListener(EventFamilyFactory & factory) : eventFactory_(factory) { }
`s/& factory/&factory/g`

2016-09-19 17:09 UTC, ohamov commented on verifiersdemo/source/cpp/src/KaaDemo.cpp
> +    std::cout << "Verifiers demo started" << std::endl;
I'd designate that any key can be pressed to stop the demo app

2016-09-21 17:04 UTC, Dubland commented
Fixed

2016-09-22 13:31 UTC, GamovCoder commented on verifiersdemo/source/cpp/src/KaaDemo.cpp
> +    std::cout << "Press Enter to stop" << std::endl;
Actually, any key stops the application: `cin.get()` waits for any key, though you'd better discuss the messages with other people which also write sample applications based on java sdk, to keep the messages consistent.

2016-09-25 13:19 UTC, Dubland commented on verifiersdemo/source/cpp/src/KaaDemo.cpp
> +    std::cout << "Press Enter to stop" << std::endl;
Done

2016-09-26 10:50 UTC, Slash32 approved these changes

2016-09-26 10:50 UTC, merged