APP-175: [Objective-C] Basic level Apps: Credentials management
kaaproject/sample-apps pull request #238
Opened 2016-09-20 09:34 UTC by am1kk

http://jira.kaaproject.org/browse/APP-175

2016-09-20 09:34 UTC, am1kk commented
@vilimets Review please.

2016-09-20 12:51 UTC, vilimets commented on credentialsdemo/source/objc/CredentialsDemo/ViewController.m
> +    self.logTextView.alpha = 100;
UIView alpha value should be number in the range 0.0 to 1.0

2016-09-20 12:52 UTC, vilimets requested changes

2016-09-21 12:48 UTC, am1kk commented on credentialsdemo/source/objc/CredentialsDemo/ViewController.m
> +    self.logTextView.alpha = 100;
Fixed.

2016-09-21 12:48 UTC, am1kk commented
@vilimets re-review please.

2016-09-21 12:50 UTC, vilimets approved these changes
LGTM

2016-09-23 12:03 UTC, vilimets approved these changes
LGTM

2016-09-26 10:39 UTC, Slash32 commented
@kaa-leeroy test this please

2016-09-26 11:37 UTC, Slash32 approved these changes

2016-09-26 11:38 UTC, merged