APP-172: GPIO app was moved from ant to gradle and updated
kaaproject/sample-apps pull request #257
Opened 2016-09-27 13:42 UTC by iamtodor

2016-09-27 17:44 UTC, Slash32 commented
@kaa-leeroy test this please

2016-09-28 14:01 UTC, maxml commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/utils/KaaProvider.java
I think this class must be named KaaManager like in other apps and must be in directory kaa/ like in other apps.

2016-09-28 14:01 UTC, maxml commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/utils/PreferencesManager.java
> +
I think, this app must be the simplest. New class for three lines - it's not unnecessary.

2016-09-28 14:01 UTC, maxml commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/model/Device.java
> +    @Override
In This class please move methos to some order - public methods, Override, private

2016-09-28 14:01 UTC, maxml commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/DevicesListActivity.java
>  /**
please, move all activities to some directory, for example ui/ Or you can use my approach and leave only one and main activity, activity which app loads. But two activities can't be in root directory

2016-09-28 14:01 UTC, maxml commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/DevicesListActivity.java
> +            PreferencesManager.setUserExternalId(this, "2");
Why 2? Why not in constant?

2016-09-28 14:01 UTC, maxml commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/DevicesListActivity.java
>      private final String TAG = DevicesListActivity.class.getSimpleName();
Please, provide some comments to this class. What does he do? Simlar to other classes - please, add comments

2016-09-28 14:01 UTC, maxml commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/DevicesListActivity.java
>      private void initViews() {
why use separate method?

2016-09-28 16:47 UTC, Slash32 requested changes
Please address the comments to the PR prior to merge.

2016-09-29 15:05 UTC, Slash32 commented
@kaa-leeroy test this please

2016-09-30 15:47 UTC, Slash32 commented
@kaa-leeroy test this please

2016-10-04 17:42 UTC, iamtodor commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/utils/KaaProvider.java
done

2016-10-04 17:43 UTC, iamtodor commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/utils/PreferencesManager.java
> +
Don't agree

2016-10-04 17:43 UTC, iamtodor commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/model/Device.java
> +    @Override
Done

2016-10-04 17:43 UTC, iamtodor commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/DevicesListActivity.java
>  /**
Done

2016-10-04 17:44 UTC, iamtodor commented on gpiocontrol/source/android/app/src/main/java/org/kaaproject/kaa/examples/gpiocontol/DevicesListActivity.java
> +            PreferencesManager.setUserExternalId(this, "2");
Have no idea what is it. I turned it to the constant.

2016-10-04 17:45 UTC, iamtodor commented
@maxml pls, review

2016-10-05 11:36 UTC, Slash32 approved these changes

2016-10-05 11:37 UTC, merged