[WIP] APP-329: [C/C++] Distinguish between CMake variables and compile definitions in cmakegen
kaaproject/sample-apps pull request #287
Opened 2016-10-03 14:33 UTC by RostakaGmfun

2016-10-04 14:03 UTC, rasendubi reviewed
Why don't we use existing template engine solutions instead of rolling our own? NIH?

2016-10-04 14:03 UTC, rasendubi commented on credentialsdemo/source/c/CMakeLists.txt
>  if (NOT DEFINED KAA_RUNTIME_KEY_GENERATION)
It's default `OFF` in the C SDK, so you may drop this.

2016-10-04 14:03 UTC, rasendubi commented on configurationdemo/source/c/CMakeLists.txt
> +if (NOT DEFINED KAA_PLATFORM)
It's default in the C SDK

2016-10-04 14:03 UTC, rasendubi commented on configurationdemo/source/c/CMakeLists.txt
> +    set(KAA_MAX_LOG_LEVEL "3")
Why string?

2016-10-04 14:09 UTC, rasendubi commented
https://www.simple-is-better.org/template/ has good list of template engines

2016-10-05 11:53 UTC, Slash32 requested changes
The questions must be addressed before merge.

2016-10-06 12:14 UTC, Slash32 commented
The PR is considered incomplete and needs re-do. The further changes will be done separately.

2016-10-06 12:14 UTC, closed without merging