APP-332: Check "Objective C Endpoint Ownership Demo" and include it to sandbox
kaaproject/sample-apps pull request #297
Opened 2016-10-06 14:03 UTC by am1kk

Don't merge.

2016-10-07 17:06 UTC, Slash32 requested changes
There are questions to the PR that must be resolved before merge.

2016-10-07 17:06 UTC, Slash32 commented on verifiersdemo/resources/projects.xml
> +        <bundleId>verifiers_demos</bundleId>
Why is the bundleId dropped here?

2016-10-07 17:06 UTC, Slash32 commented on verifiersdemo/resources/projects.xml
> +        <complexity>REGULAR</complexity>
This application is of BASIC complexity type.

2016-10-07 17:50 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-07 18:11 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-07 18:11 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-10-07 18:16 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-07 18:23 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 13:51 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 13:59 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 16:00 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 16:00 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-10-10 16:06 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 16:20 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 18:15 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 18:27 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 18:40 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 19:20 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-10 19:24 UTC, Oldnickus commented
@kaa-leeroy test this hard please

2016-10-13 08:49 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-13 09:54 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-13 10:14 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-13 10:24 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-13 18:04 UTC, Slash32 approved these changes

2016-10-13 18:05 UTC, merged