APP-235: [Java] Basic level Apps: Events
kaaproject/sample-apps pull request #300
Opened 2016-10-07 12:09 UTC by Rib47

2016-10-07 14:34 UTC, Dubland commented on eventdemo/resources/chatEventClassFamily.json
> +[
Why u add chatEventClassFamily.json? We have chat_event_class_event.avsc and chat_event_class_message.avsc in eventdemo/resources folder

2016-10-10 09:39 UTC, Slash32 requested changes
The comments must be addressed before merge.

2016-10-10 10:10 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-10-10 10:15 UTC, Rib47 commented on eventdemo/resources/chatEventClassFamily.json
> +[
You would better ask "Why you don't delete these **chat_event_class_event.avsc** and **chat_event_class_message.avsc** files from **eventdemo/resources** folder?" 
They are not used in **EventDemoBuilder**.

Fixed.

2016-10-12 14:36 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-12 15:09 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-12 18:17 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-12 18:39 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-12 18:48 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-12 18:50 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-12 18:57 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-12 20:27 UTC, vadimol commented
@kaa-leeroy test this hard please

2016-10-13 18:16 UTC, Slash32 approved these changes

2016-10-13 18:17 UTC, merged