App 88
kaaproject/sample-apps pull request #301
Opened 2016-10-07 12:59 UTC by RostakaGmfun

/cc @Slash32 @vadimol

2016-10-10 10:27 UTC, GamovCoder commented on gpiocontrol/source/c/CMakeLists.txt
> +if (${KAA_PRODUCE_BINARY})
why did you add a space?

2016-10-10 10:32 UTC, GamovCoder commented on common/c/targets/common/target_gpio_led.h
> + * console and target initialisation routines, but it must be extended
`s/initialisation/initialization`

2016-10-10 10:33 UTC, GamovCoder commented on common/c/targets/common/target_gpio_led.h
> + * console and target initialisation routines, but it must be extended
`s/must/can` or remove `if required`

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/common/target_gpio_led.h
> +#endif // TARGET_SUPPORT_H
comment is off

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/common/target_gpio_led.h
> + * Zero status mewans LOW, positive status means HIGH
Zero -> 0
mewans -> means

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/common/target_gpio_led.h
> +/*
Why not doxygen

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/esp8266/driver/gpio.h
> +    } while(0);
do-while(0) should be used as follows. (Note the absence of trailing semicolon.)
```c
do {
    ...
} while (0)
```

Furthermore, do-while is actually not needed for single function invocation. The next would be enough:
```c
#define GPIO_OUTPUT_SET(gpio_no, bit_value) \
    gpio_output_conf((bit_value)<<(gpio_no), ((~(bit_value))&0x01)<<(gpio_no), 1<<(gpio_no), 0)
```

Also, add spaces around operators.

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/esp8266/driver/gpio.h
> +    } while(0);
Same here: remove semicolon

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/esp8266/target.h
> +#undef getchar
Care to explain?

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/esp8266/target_gpio_led.c
> +void target_gpio_led_init(void) {
Code style

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/esp8266/target_gpio_led.c
> +void target_gpio_led_toggle(int id, int status) {
Code style

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/esp8266/target_gpio_led.c
> +    if(id >= NUM_GPIO_LEDS || id < 0) {
code style

2016-10-10 10:37 UTC, rasendubi commented on common/c/targets/esp8266/target_gpio_led.c
> +    if(status) {
Code style

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/assembly/src-android.xml
> +    <id>gpiocontrol-src-android</id>
Not relevant to the PR

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/assembly/src-c.xml
> +            <directory>${main.dir}/common/c/</directory>
I wonder why nix is removed

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/CMakeLists.txt
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=gnu99 -g -Wall -Wextra")
We should stick with `-std=c99` and don't use gnu extensions as much as possible

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/CMakeLists.txt
> +    file(WRITE ${CMAKE_BINARY_DIR}/blank.c "")
Use `CMAKE_CURRENT_BINARY_DIR`

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/CMakeLists.txt
> +if("${KAA_TARGET}" STREQUAL "esp8266")
Explanation is missing

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/CMakeLists.txt
> +if (${KAA_PRODUCE_BINARY})
code style

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +# TODO: comment about inconvenience between KAA_TARGET and KAA_PLATFORM
Should be resolved

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +    # TODO: better case handling
Resolve this TODO item or open an issue.

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +    if [[ ! -d "$KAA_C_LIB_HEADER_PATH" &&  ! -d "$KAA_CPP_LIB_HEADER_PATH" ]]
AFAIK, there is no `[[` in plain sh.

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +    if [[ $KAA_REQUIRE_CREDENTIALS = true ]]
See comment above on `[[`.

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +for cmd in $@
Use next
```sh
for cmd in "$@"; do
```

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +case "$cmd" in
Add indentation level.

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/src/kaa_demo.c
>      int i = 0;
Inline `i`

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/src/kaa_demo.c
> +    int gpio_id = event->gpio->id >= NUM_GPIO_LEDS?NUM_GPIO_LEDS:event->gpio->id;
Add spaces around operators

2016-10-10 10:37 UTC, rasendubi commented on gpiocontrol/source/c/src/kaa_demo.c
> +    int gpio_id = event->gpio->id >= NUM_GPIO_LEDS?NUM_GPIO_LEDS:event->gpio->id;
Also, add braces around condition (according to MISRA)

2016-10-10 10:39 UTC, Slash32 requested changes
The comments must be addressed before merge.

2016-10-10 14:29 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-10-10 18:56 UTC, rasendubi reviewed
Minor. Otherwise, looks good.

Have you tested all platforms after changing std to c99? This could break something.

2016-10-10 18:56 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +    if [ $KAA_REQUIRE_CREDENTIALS = true ]
Code style:
```sh
if [ $KAA_REQUIRE_CREDENTIALS = true ]; then
```

2016-10-10 18:56 UTC, rasendubi commented on common/c/targets/cc32xx/target_gpio_led.c
> +/**
Should not be doxygen comment

2016-10-11 11:12 UTC, RostakaGmfun commented
@rasendubi demo compiles fine for all targets with `c99`.

2016-10-11 12:59 UTC, rasendubi commented on common/c/targets/cc32xx/target.h
> +/**
That's file-level doxygen comment: you must add `@file`.

2016-10-11 12:59 UTC, rasendubi commented on common/c/targets/common/target_gpio_led.h
> + * This header defines generic API to access
That's file-level doxygen comment: you must add `@file`.

2016-10-11 12:59 UTC, rasendubi commented on common/c/targets/esp8266/target.h
> +/**
That's file-level doxygen comment: you must add `@file`.

2016-10-11 12:59 UTC, rasendubi commented on gpiocontrol/source/c/src/kaa_demo.c
> +    int gpio_id = event->gpio->id >= (NUM_GPIO_LEDS ? NUM_GPIO_LEDS : event->gpio->id);
This changes semantics. The previous expression was parsed as:
```c
int gpio_id = (event->gpio->id >= NUM_GPIO_LEDS) ? NUM_GPIO_LEDS : event->gpio->id;
```

That's what I meant by "around condition".

2016-10-11 12:59 UTC, rasendubi commented on gpiocontrol/source/c/src/kaa_demo.c
> +    int gpio_id = event->gpio->id >= (NUM_GPIO_LEDS ? NUM_GPIO_LEDS : event->gpio->id);
Looked into meaning. Could be replaced by `min` function/macro.

2016-10-11 15:02 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-11 20:52 UTC, rasendubi approved these changes

2016-10-13 08:04 UTC, Slash32 approved these changes

2016-10-13 08:35 UTC, Slash32 commented
@kaa-leeroy test this hard please

2016-10-13 09:24 UTC, rasendubi commented on common/c/targets/esp8266/target.h
> +#undef getchar
How this worked before?

2016-10-13 18:03 UTC, Slash32 approved these changes

2016-10-13 18:03 UTC, merged