APP-382: [Objective-C] Endpoint ownership: Application is commented in pom.xml
kaaproject/sample-apps pull request #328
Opened 2016-10-18 16:34 UTC by am1kk

http://jira.kaaproject.org/browse/APP-382

2016-10-18 16:37 UTC, am1kk commented
@hunch7 Review please.

2016-10-18 17:05 UTC, Slash32 requested changes
The projects.xml must follow .xsd schema in order to not break Sandbox.

Also, the PR should be re-based to resolve existing conflicts.

2016-10-18 17:05 UTC, Slash32 commented on verifiersdemo/resources/projects.xml
> +        <platforms></platforms>
This part must be filled correctly. Otherwise the Sandbox UI will be broken.

2016-10-18 17:05 UTC, Slash32 commented on verifiersdemo/resources/projects.xml
> +        <sourceArchive></sourceArchive>
Same as above for this and below lines.

2016-10-18 17:20 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-19 08:03 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-19 08:10 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-19 10:06 UTC, closed without merging