APP-348: Fix C++ Profiling demo
kaaproject/sample-apps pull request #329
Opened 2016-10-18 16:45 UTC by RostakaGmfun

/cc @Slash32 @Dubland

2016-10-18 16:49 UTC, Dubland commented
LGTM

2016-10-18 17:17 UTC, Slash32 requested changes
Minor nitpick, otherwise good.
Let's pass Jenkins.

2016-10-18 17:17 UTC, Slash32 commented on scripts/apptester/apps.yam
> +          buildcmd: "bash -c \"./build.sh build\""
dependency specification is missing

2016-10-18 17:17 UTC, Slash32 commented on profilingdemo/source/cpp/CMakeLists.txt
> +target_link_libraries(demo_client kaacpp ${Boost_FILESYSTEM_LIBRARY})
Doesn't this need double-quotes?

2016-10-18 17:19 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-18 18:51 UTC, RostakaGmfun commented on scripts/apptester/apps.yam
> +          buildcmd: "bash -c \"./build.sh build\""
Threre is no dependencies for C Profiling Demo, it is completely contained in `profilingdemo/source/c` directory

2016-10-19 06:52 UTC, RostakaGmfun commented on profilingdemo/source/cpp/CMakeLists.txt
> +target_link_libraries(demo_client kaacpp ${Boost_FILESYSTEM_LIBRARY})
No, it doesn't. There might be a list of libraries in this variable and we want it to expand into a space-separated list of items

2016-10-19 07:52 UTC, Slash32 commented on scripts/apptester/apps.yam
> +          buildcmd: "bash -c \"./build.sh build\""
For other applications, there is dependency to build.sh script itself.

2016-10-19 07:52 UTC, Slash32 commented
The PR does not pass Jenkins. Please check https://jenkins.kaaproject.org:52001/job/KSAs_test_sample_apps_pr/23/consoleFull

2016-10-19 08:04 UTC, RostakaGmfun commented
@kaa-leeroy test this fully please

2016-10-19 08:12 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-19 10:06 UTC, RostakaGmfun commented
@kaa-leeroy test this fully please

2016-10-19 11:47 UTC, Slash32 approved these changes

2016-10-19 11:47 UTC, merged