APP-374: Add events demo for android
kaaproject/sample-apps pull request #339
Opened 2016-10-20 11:48 UTC by tonyshkurenko

2016-10-20 17:25 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-21 12:10 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-21 12:30 UTC, tonyshkurenko commented
@kaa-leeroy test this fully please

2016-10-22 09:29 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-23 13:56 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-23 15:30 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-23 16:33 UTC, Slash32 requested changes
Please drop the icon.png file since it will conflict with the other one added in a separate PR.

2016-10-24 14:58 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-24 18:43 UTC, Slash32 requested changes
The target merge branch is release-2.1 which has not been created yet.

2016-10-25 15:55 UTC, abohomol requested changes
I recommend to make certain changes before merging.

2016-10-25 15:55 UTC, abohomol commented on eventdemo/source/android/app/src/main/java/org/kaaproject/kaa/demo/events/utils/KaaChatManager.java
> +            startupLatch.await();
The endpoint SDK enables you to have event-driven flow via appropriate callback, so why do you make those calls synchronized?

2016-10-25 15:55 UTC, abohomol commented on eventdemo/source/android/app/src/main/java/org/kaaproject/kaa/demo/events/utils/KaaChatManager.java
> +            attachLatch.await();
Same as a previous one

2016-10-25 15:55 UTC, abohomol commented on eventdemo/source/android/app/src/main/java/org/kaaproject/kaa/demo/events/utils/KaaChatManager.java
> +            startupLatch.await();
It's also stopping EventDemoApp from being created while you're waiting for result.

2016-10-25 15:55 UTC, abohomol commented on eventdemo/source/android/app/src/main/java/org/kaaproject/kaa/demo/events/dialogfragments/InputTextDialogFragment.java
> +     * @param hint hint has a second function,
Although, the second function of anything is a bad practice it's event worse to give that to a hint of EditText.

2016-10-25 15:55 UTC, abohomol commented on eventdemo/source/android/app/src/main/java/org/kaaproject/kaa/demo/events/dialogfragments/InputTextDialogFragment.java
> +        builder.setTitle("Input text");
Apart from demonstrating the best practices of endpoint SDK usage application should also demonstrate solid Android skills, so please replace all literals with string resources.

2016-10-25 15:55 UTC, abohomol commented on eventdemo/source/android/app/src/main/java/org/kaaproject/kaa/demo/events/dialogfragments/InputTextDialogFragment.java
> +public final class InputTextDialogFragment extends DialogFragment {
Isn't that cheaper to create a dialog using the "AlertDialog.Builder" and set EditText to its view?

2016-10-25 21:07 UTC, closed without merging