APP-403: [Java] Credentials demos fix bugs in apps and documentation
kaaproject/sample-apps pull request #371
Opened 2016-10-26 13:15 UTC by Rib47

…Remove needless dependencies.

2016-10-26 14:42 UTC, makswinner approved these changes

2016-10-27 09:34 UTC, Slash32 requested changes
Small question, otherwise good.

2016-10-27 09:34 UTC, Slash32 commented on credentialsdemo/assembly/src-java.xml
> -    <dependencySets>
Please identify why is this dropped?

2016-10-27 09:35 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-10-27 13:17 UTC, Rib47 commented on credentialsdemo/assembly/src-java.xml
> -    <dependencySets>
This section copies dependencies that needed only for Admin application.
Client application do not need them.

2016-10-27 13:18 UTC, Slash32 commented on credentialsdemo/assembly/src-java.xml
> -    <dependencySets>
Thanks for the explanation

2016-10-27 14:24 UTC, Slash32 approved these changes

2016-10-27 14:54 UTC, merged