APP-330: Configuration Demo does not display seconds in the sampling period.
kaaproject/sample-apps pull request #418
Opened 2016-11-01 13:45 UTC by am1kk

http://jira.kaaproject.org/browse/APP-330

2016-11-01 13:45 UTC, am1kk commented
@Slash32 Review please.

2016-11-02 14:13 UTC, Slash32 commented
@kaa-leeroy test this please

2016-11-02 14:13 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-02 14:15 UTC, Slash32 requested changes

2016-11-02 14:15 UTC, Slash32 commented on configurationdemo/source/objc/ConfigurationDemo/ViewController.m
> +    [self addLogWithText:[NSString stringWithFormat:@"Sampling period is %d sec.", configuration.samplePeriod]];
Please folllow the rules used in the Bundle description. E.g.:

`[pool-2-thread-1] INFO  o.k.k.d.c.ConfigurationDemo - Sampling period is now set to 10 seconds`

2016-11-02 14:49 UTC, am1kk commented
@Slash32 re-review please.

2016-11-02 16:41 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-02 16:41 UTC, Slash32 approved these changes

2016-11-03 13:17 UTC, Slash32 approved these changes

2016-11-03 13:17 UTC, merged