KSB-19 New fixes in apptester
kaaproject/sample-apps pull request #442
Opened 2016-11-07 14:37 UTC by socallmemaybe

2016-11-07 15:54 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-07 16:41 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-07 17:43 UTC, vadimol requested changes

2016-11-07 17:43 UTC, vadimol commented on scripts/apptester/apptester.py
> +                        elif not build_app_result:
There are two options only: True and False.
So:
if build_app_result:
...
else:
...

2016-11-07 17:43 UTC, vadimol commented on scripts/apptester/apptester.py
> +                        build_app_result = self.sandboxframe.is_build_successful(item['id'])
You can receive an exception here. You should catch here.

2016-11-07 17:43 UTC, vadimol commented on scripts/apptester/apptester.py
> +        for app in self.result_matrix:
This is a dirty hack. Let's discuss a better way to process results

2016-11-07 17:43 UTC, vadimol commented on scripts/apptester/apptester.py
>                  print type(ex), ex
This is redundant here. You should narrow the scope of the exception handling.

2016-11-07 18:37 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-08 13:38 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-08 13:55 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-09 15:59 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-09 20:04 UTC, closed without merging