APP-475: [C++] Different behavior and output of Notification Demo on various SDK clients
kaaproject/sample-apps pull request #480
Opened 2016-11-22 08:34 UTC by RostakaGmfun

/cc @Slash32 @GamovCoder

2016-11-22 10:09 UTC, Slash32 commented
@kaa-leeroy test this please

2016-11-22 11:07 UTC, ohamov requested changes

2016-11-22 11:07 UTC, ohamov commented on notification/source/cpp/src/KaaDemo.cpp
> +        for (;;) {
`while(true)`

2016-11-22 11:07 UTC, ohamov commented on notification/source/cpp/src/KaaDemo.cpp
> +            int topicId;
`int64_t`

2016-11-22 11:07 UTC, ohamov commented on notification/source/cpp/src/KaaDemo.cpp
> +                topicId = std::stoi(input);
`stoll`

2016-11-22 11:07 UTC, ohamov commented on notification/source/cpp/src/KaaDemo.cpp
> +            } catch(std::exception& e) {
code style

2016-11-22 11:07 UTC, ohamov commented on notification/source/cpp/src/KaaDemo.cpp
> +    std::atomic_bool quitFlag{false};
Use conditional variable.

2016-11-22 11:07 UTC, ohamov commented on notification/source/cpp/src/KaaDemo.cpp
>      virtual void onNotification(const int64_t topicId, const KaaNotification &notification)
btw, remove `virtual`, add `override`

2016-11-22 11:07 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +            std::cout << (boost::format("Subscribed to topic '%1%'") % topicId) << std::endl;
Just wonder, what is the case the message is going to be printed?

2016-11-22 11:07 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +                return;
So, I can subscribe only once?

2016-11-22 11:07 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +            std::cin >> input;
I'd like to subscribe for a several topics.

2016-11-22 12:28 UTC, RostakaGmfun commented on notification/source/cpp/src/KaaDemo.cpp
> +        for (;;) {
Don't you think it's a matter of preference? Do we have such requirements in code style guide?

2016-11-22 12:29 UTC, RostakaGmfun commented on notification/source/cpp/src/KaaDemo.cpp
> +                return;
It appears to be so according to the bundle scenario flow

2016-11-22 13:48 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +            } catch(std::exception& e) {
code style

2016-11-22 13:49 UTC, ohamov commented on notification/source/cpp/src/KaaDemo.cpp
> +                return;
Is it allowed to choose only one of the available topics to subscribe for?

2016-11-22 13:51 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +        for (;;) {
It's just a nitpick, but `while (true)` it's a common way to express an infinite loop.

2016-11-23 10:18 UTC, RostakaGmfun commented on notification/source/cpp/src/KaaDemo.cpp
> +                return;
Yes, according to the bundle scenario flow

2016-11-23 12:51 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +                return;
Ok

2016-11-23 13:58 UTC, ohamov requested changes
I think there is a deadlock now - a topic list can be received before the listeners are added.

2016-11-25 12:13 UTC, ohamov approved these changes
LGTM

2016-11-28 20:55 UTC, Slash32 commented
@kaa-leeroy test this please

2016-11-29 12:37 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-29 14:26 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-29 17:00 UTC, merged