APP-463: [C SDK] GPIO control slave application
kaaproject/sample-apps pull request #483
Opened 2016-11-22 13:00 UTC by vnerozin

Add client application for GPIO control for posix "platform"

Review: @Slash32 and @AlexShev76

2016-11-29 19:11 UTC, Slash32 requested changes
@vnerozin this also needs changes to the gpiocontrol/pom.xml and other parts for integration into the bundle.

2016-11-29 19:11 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-29 21:27 UTC, rasendubi commented on gpiocontrol/source/c/CMakeLists.txt
> +if("${KAA_PLATFORM}" STREQUAL “posix”)
`s/“posix”/"posix"/`

2016-11-29 21:27 UTC, rasendubi commented on common/c/targets/posix/target_gpio_led.c
> +    for (n = 0; n < NUM_GPIO_LEDS; n++) {
(minor) Inline `n` declaration.

2016-11-29 21:27 UTC, rasendubi commented on common/c/targets/posix/target_gpio_led.c
> +    for (n = 0; n < NUM_GPIO_LEDS; n++) {
(minor) Inline `n` declaration.

2016-11-29 21:27 UTC, rasendubi commented on common/c/targets/posix/CMakeLists.txt
> +target_include_directories(target_support PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../common)
Shouldn't this be private?

2016-11-29 21:27 UTC, rasendubi commented on common/c/targets/posix/target_gpio_led.c
> +        gpio_led_status[n] = false;
`gpio_led_status` is a static variable and is initialized with zeros by default.

2016-11-29 21:27 UTC, rasendubi commented on gpiocontrol/source/c/build.sh
> +        KAA_PRODUCE_BINARY=true
Why we need `.bin` files for POSIX?

2016-11-30 11:40 UTC, vnerozin commented on gpiocontrol/source/c/CMakeLists.txt
> +if("${KAA_PLATFORM}" STREQUAL “posix”)
Fixed

2016-11-30 11:40 UTC, vnerozin commented on common/c/targets/posix/target_gpio_led.c
> +    for (n = 0; n < NUM_GPIO_LEDS; n++) {
Fixed.

2016-11-30 11:40 UTC, vnerozin commented on common/c/targets/posix/target_gpio_led.c
> +        gpio_led_status[n] = false;
Fixed

2016-11-30 11:41 UTC, vnerozin commented on common/c/targets/posix/target_gpio_led.c
> +    for (n = 0; n < NUM_GPIO_LEDS; n++) {
Fixed.

2016-11-30 11:41 UTC, vnerozin commented on common/c/targets/posix/CMakeLists.txt
> +target_include_directories(target_support PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../common)
I have issued with PRIVITE. In this case it cannot find headers inside specific platform folder

2016-11-30 11:42 UTC, vnerozin commented on gpiocontrol/source/c/build.sh
> +        KAA_PRODUCE_BINARY=true
We do not. Fixed

2016-11-30 11:46 UTC, rasendubi commented on gpiocontrol/source/c/CMakeLists.txt
> +if("${KAA_PLATFORM}" STREQUAL "posix")
oops. I've missed this disables producing binaries for all non-posix platforms. (Basically, all platforms we want binaries for.)

2016-11-30 11:54 UTC, vnerozin commented on gpiocontrol/source/c/CMakeLists.txt
> +if("${KAA_PLATFORM}" STREQUAL "posix")
Fixed.

2016-11-30 12:20 UTC, rasendubi approved these changes

2016-12-01 20:00 UTC, Slash32 approved these changes

2016-12-01 20:00 UTC, merged