APP-474: Review fixes
kaaproject/sample-apps pull request #487
Opened 2016-11-23 11:00 UTC by RostakaGmfun

/cc @GamovCoder

2016-11-23 11:54 UTC, Slash32 commented
@kaa-leeroy test this please

2016-11-23 12:29 UTC, ohamov requested changes
There are comments which haven't been addressed.

2016-11-23 12:29 UTC, GamovCoder commented on notification/source/c/src/kaa_demo.c
>      return atoi(input);
Here you still have a problem. `atoi()` returns `int`.

2016-11-23 12:29 UTC, GamovCoder commented on notification/source/c/src/kaa_demo.c
> +        demo_printf("Notification for topic id '%li' received\r\n", *topic_id);
`%li` is for `long int`. `sizeof(long int)` for x86_64 is 4. Have you seen my previous comment?

2016-11-23 12:29 UTC, GamovCoder commented on notification/source/c/src/kaa_demo.c
> +        demo_printf("Topic: id '%li', name: %s, type: ", topic->id, topic->name);
same

2016-11-23 12:29 UTC, GamovCoder commented on notification/source/c/src/kaa_demo.c
> +                demo_printf("Subscribed to optional topic '%li'\r\n", topic->id);
same

2016-11-23 12:39 UTC, ohamov commented on notification/source/c/src/kaa_demo.c
> +static int64_t read_topic_id(void)
topic id type is not `int64_t`

2016-11-23 15:29 UTC, GamovCoder commented on notification/source/c/src/kaa_demo.c
> +    return t->id == *(int64_t*)context;
topic id type is `unint64_t`

2016-11-23 15:34 UTC, RostakaGmfun commented on notification/source/c/src/kaa_demo.c
> +static int64_t read_topic_id(void)
But in #481  you've said, it is `int64_t`. Also, `int64_t` is used for topic ids in C++ SDK. (correct me if I'm wrong)

2016-11-23 17:24 UTC, GamovCoder commented on notification/source/c/src/kaa_demo.c
> +static int64_t read_topic_id(void)
Yep, I looked at C++ SDK. Anyway, in C it is `uint64_t` type. so fix it please

2016-11-23 17:26 UTC, RostakaGmfun commented on notification/source/c/src/kaa_demo.c
>      return atoi(input);
I will rebase on master as soon as #484 is merged

2016-11-24 19:27 UTC, ohamov approved these changes
LGTM

2016-11-28 17:19 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-28 20:36 UTC, Slash32 commented
@kaa-leeroy test this fully please

2016-11-29 12:36 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-01 15:01 UTC, Slash32 approved these changes

2016-12-01 15:02 UTC, merged