APP-475: QA Review fixes
kaaproject/sample-apps pull request #521
Opened 2016-12-02 15:18 UTC by RostakaGmfun

/cc @Slash32 @socallmemaybe @GamovCoder

2016-12-05 08:39 UTC, rasendubi commented
`QA Review fixes` is not a good description. Please, describe what has been found and what this commit does. (Basically, you're rarely interested in how the issue was found.)

2016-12-06 12:50 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-06 14:13 UTC, Slash32 commented
@socallmemaybe @GamovCoder @rasendubi please review.

2016-12-07 13:30 UTC, ohamov requested changes

2016-12-07 13:30 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +        } catch (KaaException &e) {
const

2016-12-07 13:30 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +    for (;;) {
while(true)

2016-12-07 13:30 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +        } catch(std::exception& e) {
cs, const

2016-12-07 13:30 UTC, GamovCoder commented on notification/source/cpp/src/KaaDemo.cpp
> +            return 0;
use `EXIT_FAILURE` or `EXIT_SUCCESS` everywhere along the demo.

2016-12-09 10:20 UTC, am1kk commented
@kaa-leeroy test this please

2016-12-12 13:52 UTC, merged