APP-406: Fix Profiling and grouping demos description
kaaproject/sample-apps pull request #534
Opened 2016-12-05 16:23 UTC by am1kk

http://jira.kaaproject.org/browse/APP-406

2016-12-05 16:23 UTC, am1kk commented
Don't merge please

2016-12-05 16:39 UTC, hunch7 commented on profilingdemo/resources/projects.xml
> +		Select the <b>Endpoint client profile schema</b> by clicking on the corresponding row.
s/client-side profile schema of the endpoint
See the last bullet of this section please: http://kaaproject.github.io/kaa/docs/v0.10.0/Customization-guide/How-to-contribute/Style-guide/#grammar

2016-12-05 16:39 UTC, hunch7 commented on profilingdemo/resources/projects.xml
> +		The <b>Endpoint client profile schema</b> is included in the Sandbox for demonstration purpose.
s/Client-side profile schema of the endpoint

2016-12-05 16:40 UTC, hunch7 commented on profilingdemo/resources/projects.xml
> +	The same data structure is used for the <b>endpoint server profile schema</b>.
s/server-side profile schema of the endpoint

2016-12-05 16:41 UTC, hunch7 commented on profilingdemo/resources/projects.xml
> +	To view and edit this schema in the Administration UI, open the <b>Configuration</b> page under the <b>Schemas</b> section of your application and select the <b>Configuration schema</b>.
s/configuration schema

2016-12-05 16:42 UTC, hunch7 requested changes
Please see my comments.

2016-12-05 17:32 UTC, hunch7 approved these changes

2016-12-06 11:59 UTC, Slash32 approved these changes

2016-12-06 12:41 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-06 12:50 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-06 14:13 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-08 18:20 UTC, merged