APP-489: Wrong label of GPIO control demo
kaaproject/sample-apps pull request #551
Opened 2016-12-07 15:43 UTC by Dubland

/cc @Slash32

2016-12-07 15:43 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-12-07 17:08 UTC, Slash32 requested changes

2016-12-07 17:08 UTC, Slash32 commented on gpiocontrol/resources/projects.xml
> +    <bundle id="gpiocontrol_demo">
This should not be fixed by a roll-back of the bundle Id and naming. Instread, please move the resources bundle directory together with the icon to fix this, please.

2016-12-08 18:10 UTC, Slash32 approved these changes

2016-12-08 18:10 UTC, merged