APP-464: [C++ SDK] GPIO control slave application
kaaproject/sample-apps pull request #563
Opened 2016-12-09 12:09 UTC by vnerozin

Add CPP posix demo source code;

Review: @Slash32 and @rasendubi

2016-12-09 12:09 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-12-09 12:18 UTC, RostakaGmfun commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +    RemoteControlECF &remote;
Append underscore `_` to private members

2016-12-09 12:18 UTC, RostakaGmfun commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        for (std::size_t i = 0; i < leds.size(); ++i) {
Please prefer range-based for loop in C++11

2016-12-09 12:19 UTC, RostakaGmfun commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        printf("GPIO LED status: ");
Please prefer `std::cout`/`std::cin` over `printf`/`scanf`

2016-12-09 12:21 UTC, RostakaGmfun commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        std::this_thread::sleep_for(std::chrono::seconds(1));
You can omit sleep here. Infinite loop with empty body does the job well

2016-12-09 12:21 UTC, RostakaGmfun commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +    return 0;
Please use `EXIT_SUCCESS`

2016-12-09 12:22 UTC, RostakaGmfun commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +    void printLedStatus(void)
`void` in place of argument list is not required in C++

2016-12-09 13:23 UTC, Slash32 commented
@kaa-leeroy add to whitelist

2016-12-09 13:50 UTC, rasendubi commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        std::this_thread::sleep_for(std::chrono::seconds(1));
Please, don't. Busy-looping wastes processor time, while this one does not.

2016-12-09 14:07 UTC, vnerozin commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +    void printLedStatus(void)
Fixed.

2016-12-09 14:18 UTC, vasner commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +    return 0;
Fixed.

2016-12-09 14:18 UTC, vnerozin commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        std::this_thread::sleep_for(std::chrono::seconds(1));
Ok!

2016-12-09 14:18 UTC, vasner commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        printf("GPIO LED status: ");
Fixed.

2016-12-09 14:18 UTC, vasner commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +    RemoteControlECF &remote;
Fixed.

2016-12-09 14:25 UTC, vnerozin commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        for (std::size_t i = 0; i < leds.size(); ++i) {
@RostakaGmfun, please, do not forget about, example :)

2016-12-09 21:47 UTC, vnerozin commented on gpiocontrol/source/cpp/src/KaaDemo.cpp
> +        for (std::size_t i = 0; i < leds.size(); ++i) {
Fixed.

2016-12-10 12:22 UTC, Slash32 requested changes

2016-12-10 12:22 UTC, Slash32 commented on gpiocontrol/resources/projects.xml
> +        <sourceArchive>cpp-slave/gpiocontrol_demo.tar.gz/sourceArchive>
Please fix xml closing tag

2016-12-11 19:09 UTC, vnerozin commented on gpiocontrol/resources/projects.xml
> +        <sourceArchive>cpp-slave/gpiocontrol_demo.tar.gz/sourceArchive>
Fixed.

2016-12-12 18:41 UTC, Slash32 requested changes
The move to CMakeLists.txt is not fully completed. 

Also, the application configuration fails the Jenkins build.

Please update the PR accordingly.

2016-12-12 18:41 UTC, Slash32 commented on gpiocontrol/assembly/src-cpp-slave.xml
> +                <include>build.sh</include>
The build process is now moved to CMakeLists.txt use (See APP-505 and #564 ). The build.sh way is now obsolete and should not be used. Please update the build process accordngly.

2016-12-12 18:41 UTC, Slash32 commented on gpiocontrol/resources/projects.xml
> +$ ./build.sh
This should be also changed to CMakeList.txt

2016-12-12 20:02 UTC, vnerozin commented on gpiocontrol/assembly/src-cpp-slave.xml
> +                <include>build.sh</include>
Fixed.

2016-12-12 20:02 UTC, vnerozin commented on gpiocontrol/resources/projects.xml
> +$ ./build.sh
Fixed.

2016-12-13 17:24 UTC, Slash32 commented
The PR has been re-based onto master as #575 
Also there was fixed gpiocontrol build

2016-12-13 17:24 UTC, closed without merging