APP- 510: Extend apptester.py and related test suits to all the applications coverage.
kaaproject/sample-apps pull request #572
Opened 2016-12-12 20:21 UTC by socallmemaybe

1) Extended kaautils.py with new REST methods, and added possibility to check build of source.
2) Modified apptester.py (added validation of source build for all application which have it.)

2016-12-12 20:22 UTC, kaa-leeroy commented
Can one of the admins verify this patch?

2016-12-13 08:28 UTC, vadimol requested changes
See comments. Overall, looks good.

2016-12-13 08:28 UTC, vadimol commented on scripts/apptester/apptester.py
> +        self.BINARY = 'BINARY'
These properties are not logically connected with AppTesterFramework. Consider to move them to a separate class (for example AppFormat). The format is a property of the application.

2016-12-13 08:28 UTC, vadimol commented on scripts/apptester/apptester.py
> +    def execute_build(self, app_data, file_type):
I would suggest renaming this method to "execute_remote_build" or something like this.

2016-12-13 08:28 UTC, vadimol commented on scripts/apptester/apptester.py
> +    def build_all_demo(self):
This method actually does not build all of the demos. Based on code bellow, I would recommend to rename it to "check_src_archives" or "verify_src_archives"

2016-12-13 08:28 UTC, vadimol commented on scripts/apptester/apptester.py
> +        for app in self.result_matrix:
Is this related to APP-510?

2016-12-13 08:28 UTC, vadimol commented on scripts/apptester/apptester.py
> +    parser.add_argument('-c', help='build all source applications.',
This must be tested on Jenkins

2016-12-13 08:28 UTC, vadimol commented on scripts/apptester/kaautils.py
> +    def create_configuration(self, kaauser, configuration):
Are these changes related to APP-510?

2016-12-13 08:28 UTC, vadimol commented on scripts/apptester/apptester.py
> +        tester.build_java_android_demo()
We need to add additional phase on Jenkins that will run the apptester with "-c" option.

2016-12-13 11:21 UTC, socallmemaybe commented on scripts/apptester/apptester.py
> +        for app in self.result_matrix:
Yes, it was made for simplify result processing after adding new test.

2016-12-13 11:49 UTC, mariangavlytskiy commented on scripts/apptester/kaautils.py
> +    def create_configuration(self, kaauser, configuration):
No, these methods were made before for future testing of applications.

2016-12-13 11:51 UTC, Slash32 requested changes
Please re-base all the commits onto master avoiding merge commits.

2016-12-13 16:39 UTC, Slash32 commented
@kaa-leeroy add to whitelist

2016-12-13 16:49 UTC, closed without merging