APP-474: Add topic name for received notifications
kaaproject/sample-apps pull request #578
Opened 2016-12-14 15:35 UTC by RostakaGmfun

/cc @Slash32

2016-12-14 17:30 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-14 19:11 UTC, ohamov requested changes

2016-12-14 19:11 UTC, GamovCoder commented on notificationdemo/source/c/src/kaa_demo.c
> +    kaa_list_node_t *t = kaa_list_find_next(kaa_list_begin(topic_list), find_topic_predicate, topic_id);
Check search result

2016-12-14 19:23 UTC, RostakaGmfun commented on notificationdemo/source/c/src/kaa_demo.c
> +    kaa_list_node_t *t = kaa_list_find_next(kaa_list_begin(topic_list), find_topic_predicate, topic_id);
Should we expect notifications for topics we are not subscribed to?

2016-12-15 13:14 UTC, rasendubi commented on notificationdemo/source/c/src/kaa_demo.c
>      if (topic && topic->subscription_type == OPTIONAL_SUBSCRIPTION) {
`topic` was dereferenced before checking for `NULL`. (Dereferenced in line 127.)

2016-12-16 16:28 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-21 18:52 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-21 20:17 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-22 10:49 UTC, Slash32 approved these changes

2016-12-22 10:49 UTC, merged