APP-480: [C++] Fix credentials demo
kaaproject/sample-apps pull request #579
Opened 2016-12-14 16:11 UTC by Dubland

/cc @Slash32

2016-12-14 16:58 UTC, ohamov reviewed
A nitpick.

2016-12-14 16:58 UTC, GamovCoder commented on credentials/source/cpp/src/KaaDemo.cpp
> +    void onConnectionEstablished(const EndpointConnectionInfo& connection)
please add `override`

2016-12-14 19:05 UTC, ohamov requested changes
I bet it is not compiled now. Check access modifiers inside of `StateListener`.

2016-12-14 19:30 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-14 20:26 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-15 13:42 UTC, Dubland commented
@kaa-leeroy test this please

2016-12-15 18:22 UTC, GamovCoder commented on credentials/source/cpp/src/KaaDemo.cpp
> +    void onConnectionEstablished(const EndpointConnectionInfo& connection) override
should be public

2016-12-16 15:15 UTC, Dubland commented
tested with demo application

2016-12-16 16:28 UTC, Slash32 commented
@kaa-leeroy test this please

2016-12-16 17:16 UTC, Slash32 approved these changes

2016-12-16 17:16 UTC, merged