Created GPIO C master application on POSIX
kaaproject/sample-apps pull request #632
Opened 2017-02-14 17:35 UTC by sparadiuk

2017-02-16 13:16 UTC, vadimol requested changes
Not ready to be merged. See comments.

Also, add proper configurations to enable the building of the application during the building of the Sample Application project. 
Also, this can be (and should be) checked on Jenkins.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/config.cmake
> +set(WITH_EXTENSION_USER OFF CACHE BOOL "")
You should not be able to use `kaa_user_manager_default_attach_to_user` and other user specific functions if you disable the user extension.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    error_code = kaa_user_manager_default_attach_to_user(kaa_client_get_context(kaa_client)->user_manager, KAA_USER_ID, KAA_USER_ACCESS_TOKEN);
I doubt that this code is compilable with cmake file you have provided.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    gpio_status  = kaa_list_get_data(kaa_list_begin(event->gpio_status));
I don't get it. You print the status of the first GPIO in the list. What is the point? What is about other GPIOs?

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Erorr set values\n");
It is "Error".

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Erorr pin ID:  %d\n", id);
It is "Error"

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    char command[21];
Please, try to avoid magic numbers. Add a proper define for this.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("IErorr set values\n");
It is "Error".

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    if (!strcmp(command, "toggle")) {
Prefer `strncmp`

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    } else if (!strcmp(command, "status")) {
Prefer strncmp

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Fail command ..\n");
`Invalid` or `incorrect` is better here.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    kaa_error_t error_code = -1;
Use KAA_ERR_GENERIC.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    char endpoint_access_token[40];
Avoid using of the magic numbers.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    size = demo_scanf("%39s", endpoint_access_token);
Why do you need KAA_USER_ACCESS_TOKEN?

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Erorr set value\n");
It is "Error".

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    if (error_code) {
It is a stupid "copy-paste". Please, review your code before submitting.

2017-02-16 13:16 UTC, vadimol commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Failed attach to endpoint(: %i\r\n", error_code);
Remove redundant "(".

2017-02-16 13:24 UTC, GamovCoder commented on gpiocontrol/source/posix/config.cmake
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99  -pthread -lm  -g -Wall -Wextra")
`Wpedantic`

2017-02-17 15:29 UTC, rasendubi commented on gpiocontrol/source/posix/config.cmake
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99  -pthread -lm  -g -Wall -Wextra")
`-Werror` should only be enabled for development/CI. A different version of the compiler could easily break the build if `-Werror` is set unconditionally.

2017-02-17 16:29 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    gpio_status  = kaa_list_get_data(kaa_list_begin(event->gpio_status));
Sorry, I have fix it and will update

2017-02-17 16:57 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Erorr set values\n");
have fixed

2017-02-17 16:57 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Erorr pin ID:  %d\n", id);
have fixed

2017-02-17 16:57 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Erorr pin ID:  %d\n", id);
have fixed

2017-02-17 16:58 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    char command[21];
Added a define

2017-02-17 16:58 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("IErorr set values\n");
Have fixed

2017-02-17 16:58 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    if (!strcmp(command, "toggle")) {
changed

2017-02-17 16:58 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    } else if (!strcmp(command, "status")) {
Changed

2017-02-17 16:59 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Fail command ..\n");
Changed to "An incorrect command"

2017-02-17 16:59 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    char endpoint_access_token[40];
Added a define

2017-02-17 17:00 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    kaa_error_t error_code = -1;
changed

2017-02-17 17:02 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    size = demo_scanf("%39s", endpoint_access_token);
Checked, don't need. Have removed

2017-02-17 17:03 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Erorr set value\n");
Fixed

2017-02-17 17:16 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    if (error_code) {
Removed

2017-02-17 17:17 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +    error_code = kaa_user_manager_default_attach_to_user(kaa_client_get_context(kaa_client)->user_manager, KAA_USER_ID, KAA_USER_ACCESS_TOKEN);
Compiled I removed it, because it doesn't need

2017-02-17 17:20 UTC, sparadiuk commented on gpiocontrol/source/posix/src/kaa_demo.c
> +        demo_printf("Failed attach to endpoint(: %i\r\n", error_code);
Have removed

2017-02-17 17:37 UTC, sparadiuk commented on gpiocontrol/source/posix/config.cmake
> +set(WITH_EXTENSION_USER OFF CACHE BOOL "")
I enabled the flag

2017-02-28 14:03 UTC, vadimol approved these changes

2017-02-28 14:09 UTC, Slash32 approved these changes

2017-02-28 18:07 UTC, merged